#!/usr/bin/env python3
"""
High-volatility downtrend-continuation study for the short T5 universe.

This is Idea 1 from the short-side review:

- Do not mirror the long setup with low BB position + falling MACD.
- Treat inverse-V/T5 as context, then sell only when the market looks like a
  real volatility expansion / trend continuation.

The source universe is generated by run_t5_short_mirror_validation.py.
"""

from __future__ import annotations

import math
from itertools import product
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd

from run_elliott_fibo_study import markdown_table


THIS_DIR = Path(__file__).resolve().parent
SOURCE = THIS_DIR / "results_2026_05_28" / "t5_short_mirror_validation" / "short_t5_broad_trades_2015_2026.csv"
OUT_DIR = THIS_DIR / "results_2026_05_28" / "t5_short_high_vol_continuation"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def profit_factor(r: pd.Series) -> float:
    wins = float(r[r > 0].sum())
    losses = float(r[r <= 0].sum())
    if losses < 0:
        return wins / abs(losses)
    return math.inf if wins > 0 else math.nan


def max_drawdown(r: pd.Series) -> float:
    if r.empty:
        return 0.0
    curve = r.astype(float).cumsum()
    return float((curve.cummax() - curve).max())


def max_losing_streak(r: pd.Series) -> int:
    cur = 0
    best = 0
    for value in r.astype(float):
        if value <= 0:
            cur += 1
            best = max(best, cur)
        else:
            cur = 0
    return best


def metrics(df: pd.DataFrame) -> dict[str, float | int]:
    r = df["r_after_cost"].astype(float) if not df.empty else pd.Series(dtype=float)
    return {
        "trades": int(len(r)),
        "win_rate": float((r > 0).mean() * 100) if len(r) else 0.0,
        "total_r": float(r.sum()) if len(r) else 0.0,
        "avg_r": float(r.mean()) if len(r) else 0.0,
        "pf": profit_factor(r) if len(r) else math.nan,
        "max_dd_r": max_drawdown(r),
        "max_losing_streak": max_losing_streak(r),
    }


def summarize_case(name: str, df: pd.DataFrame, notes: str = "") -> dict:
    research = df[df["period"].eq("Research_2015_2024")] if not df.empty else df
    oos = df[df["period"].eq("OOS_2025_2026")] if not df.empty else df
    row = {"case": name, "notes": notes}
    row.update({f"all_{k}": v for k, v in metrics(df).items()})
    row.update({f"research_{k}": v for k, v in metrics(research).items()})
    row.update({f"oos_{k}": v for k, v in metrics(oos).items()})
    return row


FilterFn = Callable[[pd.DataFrame], pd.Series]


def as_bool(s: pd.Series) -> pd.Series:
    return s.fillna(False).astype(bool)


def named_filters() -> dict[str, tuple[FilterFn, str]]:
    return {
        "Broad short T5": (
            lambda d: pd.Series(True, index=d.index),
            "逆V候補後T5ショート全体。比較用。",
        ),
        "Mirror practical loser": (
            lambda d: (
                d["bb_pos"].between(0.05, 0.40)
                & d["signal_recovery_bars"].le(16)
                & d["macd_hist_slope3"].lt(0)
                & d["bb_width_atr"].le(7)
            ),
            "前回負けた鏡写し条件。比較用。",
        ),
        "HV core rebreak ADX25 BBW7-10 BBpos0-25": (
            lambda d: (
                d["trigger_type"].eq("rebreak")
                & d["adx14"].ge(25)
                & d["bb_width_atr"].between(7, 10)
                & d["bb_pos"].between(0, 0.25)
            ),
            "高ボラ下落継続の中心仮説。OOS発生数も確認する。",
        ),
        "HV ADX25 BBW7-10 any trigger": (
            lambda d: d["adx14"].ge(25) & d["bb_width_atr"].between(7, 10),
            "rebreak限定を外し、高ボラ・トレンド強度だけを見る。",
        ),
        "HV rebreak ADX25 BBW>=7 BBpos0-25": (
            lambda d: (
                d["trigger_type"].eq("rebreak")
                & d["adx14"].ge(25)
                & d["bb_width_atr"].ge(7)
                & d["bb_pos"].between(0, 0.25)
            ),
            "BB幅上限10ATRを外す。極端な荒れ相場が混ざるか確認。",
        ),
        "HV MACD-turn rebreak": (
            lambda d: d["trigger_type"].eq("rebreak") & d["macd_hist_slope3"].gt(0),
            "売りが伸びきった直後ではなく、MACDが下げ止まり方向のrebreakだけ。",
        ),
        "HV GBP/AUD ADX25": (
            lambda d: d["symbol"].isin(["GBPJPY", "AUDJPY"]) & d["adx14"].ge(25),
            "通貨特性を優先。GBPJPY/AUDJPYの強いトレンド化だけを見る。",
        ),
        "HV GBP/AUD ADX25 rebreak": (
            lambda d: d["symbol"].isin(["GBPJPY", "AUDJPY"]) & d["adx14"].ge(25) & d["trigger_type"].eq("rebreak"),
            "通貨特性 + rebreak。シンプルな実戦候補。",
        ),
        "HV GBP/AUD ATRpct80 rebreak": (
            lambda d: d["symbol"].isin(["GBPJPY", "AUDJPY"]) & d["atr_pctile_252"].ge(80) & d["trigger_type"].eq("rebreak"),
            "高ボラをBB幅ではなくATRパーセンタイルで見る。",
        ),
    }


def named_summary(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for name, (fn, notes) in named_filters().items():
        rows.append(summarize_case(name, df[as_bool(fn(df))], notes))
    return pd.DataFrame(rows)


def condition_grid(df: pd.DataFrame) -> pd.DataFrame:
    symbol_modes = {
        "all": lambda d: pd.Series(True, index=d.index),
        "gbp_aud": lambda d: d["symbol"].isin(["GBPJPY", "AUDJPY"]),
        "gbp_only": lambda d: d["symbol"].eq("GBPJPY"),
    }
    trigger_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "rebreak": lambda d: d["trigger_type"].eq("rebreak"),
        "not_combo": lambda d: ~d["trigger_type"].eq("stagnation+rebreak"),
    }
    adx_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "ge25": lambda d: d["adx14"].ge(25),
        "30_40": lambda d: d["adx14"].between(30, 40),
    }
    width_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "ge7": lambda d: d["bb_width_atr"].ge(7),
        "7_10": lambda d: d["bb_width_atr"].between(7, 10),
    }
    bbpos_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "le0": lambda d: d["bb_pos"].le(0),
        "0_025": lambda d: d["bb_pos"].between(0, 0.25),
    }
    macd_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "gt0": lambda d: d["macd_hist_slope3"].gt(0),
        "gt_neg001": lambda d: d["macd_hist_slope3"].gt(-0.01),
        "neg008_neg005": lambda d: d["macd_hist_slope3"].between(-0.08, -0.05),
    }
    atr_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "pct_ge80": lambda d: d["atr_pctile_252"].ge(80),
    }
    recovery_modes = {
        "any": lambda d: pd.Series(True, index=d.index),
        "gt16": lambda d: d["signal_recovery_bars"].gt(16),
        "gt24": lambda d: d["signal_recovery_bars"].gt(24),
    }

    rows = []
    groups = [
        ("symbol", symbol_modes),
        ("trigger", trigger_modes),
        ("adx", adx_modes),
        ("bb_width", width_modes),
        ("bb_pos", bbpos_modes),
        ("macd", macd_modes),
        ("atr", atr_modes),
        ("recovery", recovery_modes),
    ]
    for choices in product(*[list(options.items()) for _, options in groups]):
        labels = dict((group_name, choice_name) for (group_name, _), (choice_name, _) in zip(groups, choices))
        mask = pd.Series(True, index=df.index)
        for (_, _), (_, fn) in zip(groups, choices):
            mask &= as_bool(fn(df))
        sample = df[mask]
        if len(sample) < 8:
            continue
        row = {**labels, **summarize_case("grid", sample)}
        rows.append(row)

    grid = pd.DataFrame(rows)
    if grid.empty:
        return grid
    grid["score"] = (
        grid["all_total_r"]
        + grid["all_avg_r"] * 5
        + np.minimum(grid["all_pf"].replace(math.inf, 99), 5)
        - grid["all_max_dd_r"] * 0.2
        - np.where(grid["oos_trades"].eq(0), 2.0, 0.0)
    )
    return grid.sort_values(["score", "all_total_r"], ascending=False).reset_index(drop=True)


def by_period_year(df: pd.DataFrame, mask: pd.Series) -> pd.DataFrame:
    sample = df[as_bool(mask)].copy()
    if sample.empty:
        return pd.DataFrame()
    rows = []
    for year, group in sample.groupby("year"):
        row = {"year": year}
        row.update(metrics(group))
        rows.append(row)
    return pd.DataFrame(rows).sort_values("year")


def write_report(
    source_df: pd.DataFrame,
    named: pd.DataFrame,
    grid: pd.DataFrame,
    recommended: pd.DataFrame,
    by_year: pd.DataFrame,
) -> None:
    compact = [
        "case",
        "all_trades",
        "all_win_rate",
        "all_total_r",
        "all_avg_r",
        "all_pf",
        "all_max_dd_r",
        "research_trades",
        "research_total_r",
        "oos_trades",
        "oos_total_r",
        "notes",
    ]
    grid_cols = [
        "symbol",
        "trigger",
        "adx",
        "bb_width",
        "bb_pos",
        "macd",
        "atr",
        "recovery",
        "all_trades",
        "all_win_rate",
        "all_total_r",
        "all_avg_r",
        "all_pf",
        "all_max_dd_r",
        "oos_trades",
        "oos_total_r",
        "score",
    ]
    lines = [
        "# H4 T5 ショート: 高ボラ下落継続アイディア検証",
        "",
        "## 結論",
        "",
        "- 鏡写しのショート条件は明確に負け。",
        "- ただし `ADX高め`, `BB幅7〜10ATR`, `rebreak`, `MACD slope3>0`, `GBPJPY/AUDJPY` にはプラス断片が残る。",
        "- OOSはまだ弱い。2025-2026で発生ゼロ、または少数マイナスの候補が多いため、採用ではなく研究継続候補。",
        "",
        "## 母集団",
        "",
        f"- Source trades: {len(source_df)}",
        f"- Source file: `{SOURCE.name}`",
        "",
        "## 名前付き候補",
        "",
        markdown_table(named[compact], 40),
        "",
        "## 推奨候補の年別",
        "",
        markdown_table(by_year, 80) if not by_year.empty else "_No rows._",
        "",
        "## グリッド上位",
        "",
        markdown_table(grid[grid_cols].head(60), 80) if not grid.empty else "_No rows._",
        "",
        "## 実戦メモ",
        "",
        "- `BB幅<=4ATR` のようなロング版の安全条件は、ショートではむしろ優位性を消していた。",
        "- 下側BBに張り付いてMACDも悪い場面は売り遅れになりやすい。",
        "- 高ボラ継続ショートとして使うなら、まずはデモ/研究で `rebreak + ADX>=25 + BB幅7〜10ATR` を監視する。",
        "- OOSが不足しているため、本番採用候補ではなくフォワード観察候補。",
        "",
        "## 出力CSV",
        "",
        "- `named_candidates.csv`",
        "- `grid_candidates.csv`",
        "- `recommended_trades.csv`",
        "- `recommended_by_year.csv`",
    ]
    (OUT_DIR / "report_ja.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Run run_t5_short_mirror_validation.py first: {SOURCE}")

    df = pd.read_csv(SOURCE, parse_dates=["signal_time", "entry_time", "exit_time"])
    named = named_summary(df)
    grid = condition_grid(df)

    recommended_mask = (
        df["trigger_type"].eq("rebreak")
        & df["adx14"].ge(25)
        & df["bb_width_atr"].between(7, 10)
        & df["bb_pos"].between(0, 0.25)
    )
    recommended = df[recommended_mask.fillna(False)].copy()
    by_year = by_period_year(df, recommended_mask)

    named.to_csv(OUT_DIR / "named_candidates.csv", index=False)
    grid.to_csv(OUT_DIR / "grid_candidates.csv", index=False)
    recommended.to_csv(OUT_DIR / "recommended_trades.csv", index=False)
    by_year.to_csv(OUT_DIR / "recommended_by_year.csv", index=False)
    write_report(df, named, grid, recommended, by_year)

    print(f"Report: {OUT_DIR / 'report_ja.md'}")
    print(named[["case", "all_trades", "all_win_rate", "all_total_r", "all_avg_r", "all_pf", "oos_trades", "oos_total_r"]].to_string(index=False))
    print("\nGrid top:")
    if not grid.empty:
        print(
            grid[
                [
                    "symbol",
                    "trigger",
                    "adx",
                    "bb_width",
                    "bb_pos",
                    "macd",
                    "atr",
                    "recovery",
                    "all_trades",
                    "all_total_r",
                    "all_avg_r",
                    "all_pf",
                    "oos_trades",
                    "oos_total_r",
                ]
            ]
            .head(20)
            .to_string(index=False)
        )


if __name__ == "__main__":
    main()
