"""
通貨フィルタ別アンサンブル比較
==============================
全通貨 vs CHF/AUD除外 vs TOP5 vs TOP3 で
リスク調整後リターンがどう変化するか検証。
"""
from __future__ import annotations

import math
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "backtests/ensemble/ensemble_trades.csv"
OUT = ROOT / "backtests/ensemble"


def metrics(df: pd.DataFrame, name: str) -> dict:
    n = len(df)
    if n == 0:
        return {"name": name, "trades": 0}
    df = df.sort_values("entry_time").reset_index(drop=True)
    wins = df[df["r"] > 0]
    losses = df[df["r"] <= 0]
    pf = wins["r"].sum() / abs(losses["r"].sum()) if abs(losses["r"].sum()) > 0 else float("inf")
    win_rate = len(wins) / n * 100
    cum = df["r"].cumsum()
    dd = (cum.cummax() - cum).max()

    streak_w = streak_l = max_w = max_l = 0
    for r in df["r"]:
        if r > 0:
            streak_w += 1; streak_l = 0
        else:
            streak_l += 1; streak_w = 0
        max_w = max(max_w, streak_w); max_l = max(max_l, streak_l)

    span_days = (df["entry_time"].iloc[-1] - df["entry_time"].iloc[0]).days
    tpy = n / (span_days / 365.25) if span_days > 0 else 0
    total = df["r"].sum()
    return {
        "name": name,
        "trades": n,
        "WR_%": round(win_rate, 1),
        "PF": round(pf, 3) if math.isfinite(pf) else "inf",
        "avg_R": round(df["r"].mean(), 3),
        "total_R": round(total, 2),
        "max_DD_R": round(dd, 2),
        "Calmar": round(total / dd, 2) if dd > 0 else float("inf"),
        "MaxConsecLoss": max_l,
        "trades_per_yr": round(tpy, 1),
    }


def df_to_md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |"]
    lines.append("|" + "|".join(["---"] * len(cols)) + "|")
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            if isinstance(v, float):
                cells.append(f"{v:.3f}" if math.isfinite(v) and abs(v) < 100 else (f"{v:.2f}" if math.isfinite(v) else "inf"))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main():
    df = pd.read_csv(SRC, parse_dates=["entry_time", "exit_time"])
    df = df[df["accepted"] == True].copy()  # noqa: E712

    portfolios = {
        "ALL (全8通貨)":        list(df["symbol"].unique()),
        "EXCL_CHF_AUD (6通貨)": ["XAUUSD", "SILVER", "EURJPY", "GBPJPY", "XAGUSD", "USDJPY"],
        "TOP5 (PF>1.6)":         ["XAUUSD", "SILVER", "EURJPY", "GBPJPY", "XAGUSD"],
        "TOP3 (高Calmar)":       ["XAUUSD", "SILVER", "GBPJPY"],
        "GOLD_ONLY (XAUUSD)":    ["XAUUSD"],
    }

    rows = []
    for name, symbols in portfolios.items():
        sub = df[df["symbol"].isin(symbols)]
        m = metrics(sub, name)
        rows.append(m)

    summary = pd.DataFrame(rows)
    print("=" * 80)
    print("Portfolio Comparison (Ensemble = TrendBreakV1 + SaiBest)")
    print("=" * 80)
    print(summary.to_string(index=False))

    # 戦略別寄与もポートフォリオ別に
    detail_rows = []
    for name, symbols in portfolios.items():
        sub = df[df["symbol"].isin(symbols)]
        for strat in ["TrendBreakV1", "SaiBest"]:
            d = sub[sub["strategy"] == strat]
            m = metrics(d, f"{name} / {strat}")
            detail_rows.append(m)
    detail_df = pd.DataFrame(detail_rows)

    summary.to_csv(OUT / "portfolio_comparison.csv", index=False)
    detail_df.to_csv(OUT / "portfolio_comparison_by_strategy.csv", index=False)

    lines = ["# Portfolio Filter Comparison", "",
             "_Generated by `backtests/ensemble/run_filtered.py`_", "",
             "## ポートフォリオ別サマリー", "",
             df_to_md(summary), "",
             "## 戦略別寄与", "",
             df_to_md(detail_df), "",
             "## 解釈", "",
             "- **Calmar (= total_R / max_DD_R)** が運用品質の最重要指標",
             "- **trades_per_yr が極端に低い場合**、心理的に続かない (年5回未満は実運用厳しい)",
             "- **MaxConsecLoss が10超え**は資金規模に比して耐えられない可能性",
             ""]
    (OUT / "portfolio_comparison.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\n✅ Saved to {OUT}/portfolio_comparison.{{csv,md}}")


if __name__ == "__main__":
    main()
